services:

task-manager:
  image: jgf78/task-manager:latest
  container_name: task-manager

  ports:
    - "8087:8087"

  environment:
    DB_HOST: xxxxxxx
    DB_PORT: 5432
    DB_NAME: taskmanager
    DB_USERNAME: xxxxx
    DB_PASSWORD: xxxxx

  restart: unless-stopped