services:

  task-manager:
    image: jgf78/task-manager:latest
    container_name: task-manager

    ports:
      - "8087:8087"

    environment:

      # postgres | mongodb
      DATABASE_TYPE: mongodb

      # PostgreSQL
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: taskmanager
      DB_USERNAME: xxxxxxx
      DB_PASSWORD: xxxxxxx

      # MongoDB
      MONGODB_URI: mongodb://xxxxxx:xxxxx@mongodb:27017/taskmanager?authSource=xxxxx

    networks:
      - iagente_backend
      - mongodb_default

    restart: unless-stopped

networks:

  iagente_backend:
    external: true

  mongodb_default:
    external: true