database:
  type: postgres

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:taskmanager}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  autoconfigure:
    exclude:
      - org.springframework.boot.mongodb.autoconfigure.MongoAutoConfiguration
      - org.springframework.boot.data.mongodb.autoconfigure.DataMongoAutoConfiguration
      - org.springframework.boot.data.mongodb.autoconfigure.DataMongoRepositoriesAutoConfiguration