server:
  port: 8080

spring:
  application:
    name: task-manager

  datasource:
    url: jdbc:postgresql://jgf78japan.duckdns.org:${DB_PORT:5432}/${DB_NAME:taskmanager}
    username: iagente
    password: iagente

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true