server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]

  profiles:
    active: ${DATABASE_TYPE:postgres}

  application:
    name: task-manager

logging:
  file:
    path: ${LOG_PATH:./target/}
    name: ${spring.application.name}

  level:
    com.julian: ${LOG_LEVEL_APP:DEBUG}
    org.springframework.boot: ${LOG_LEVEL_SPRING_BOOT:INFO}
    org.springframework.web: ${LOG_LEVEL_SPRING_WEB:INFO}